application: khan-big-board
version: znd
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/mail/new-projects@khan-big-board.appspotmail.com
  script: mail.app
  login: admin
- url: /.*
  script: main.app
- url: /_ah/queue/deferred
    script: google.appengine.ext.deferred.deferred.application
    login: admin

libraries:
- name: ssl
  version: latest
- name: lxml
  version: 2.3.5
- name: pycrypto
  version: "latest"
- name: jinja2
  version: latest

inbound_services:
- mail

skip_files:
####
# Backup files/etc -- created by editors, but not part of the source tree.
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*\.orig$
- ^(.*/)?.*\.rej$
####
# Third-party
# All third_party directories that have "-src" or "-khansrc" are sym-
# linked to their non-src version (see third_party/README for details).
# The one exception is javascript-khansrc, which is handled with the
# javascript code above.
- ^third_party/.*-src$

builtins:
- deferred: on
